OUT = ft_display_file
CC = gcc
CCFLAGS = -Wall -Wextra -Werror

.PHONY: all
all: $(OUT)

$(OUT): main.c
	$(CC) $(CCFLAGS) -o $(OUT) main.c

.PHONY: clean
clean:

.PHONY: clean
fclean: clean
	rm -f $(OUT)

